version: '3'
services:
  php72: &base
    build: {dockerfile: php72/Dockerfile, context: docker}
    command: copy-project composer test
    volumes:
      - .:/project:ro

  php71:
    <<: *base
    build: {dockerfile: php71/Dockerfile, context: docker}

  php70:
    <<: *base
    build: {dockerfile: php70/Dockerfile, context: docker}

  php56:
    <<: *base
    build: {dockerfile: php56/Dockerfile, context: docker}

  php55:
    <<: *base
    build: {dockerfile: php55/Dockerfile, context: docker}

  php54:
    <<: *base
    build: {dockerfile: php54/Dockerfile, context: docker}

  php53:
    <<: *base
    build: {dockerfile: php53/Dockerfile, context: docker}
